[project]
name = "stock-statistical-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyter>=1.1.1",
    "lxml>=6.0.2",
    "plotly>=6.3.1",
    "yfinance>=0.2.66",
]
