[project]
name = "stock-statistical-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "backtesting>=0.6.5",
    "dukascopy-python>=4.0.1",
    "hmmlearn>=0.3.3",
    "jupyter>=1.1.1",
    "lxml>=6.0.2",
    "matplotlib>=3.10.7",
    "metatrader5>=5.0.5430; sys_platform == 'win32'",
    "oandapyv20>=0.7.2",
    "pandas>=2.3.3",
    "pandas-ta>=0.4.71b0",
    "plotly>=6.3.1",
    "pyarrow>=23.0.1",
    "python-dotenv>=1.2.1",
    "pytz>=2025.2",
    "quantstats>=0.0.77",
    "scikit-learn>=1.7.2",
    "seaborn>=0.13.2",
    "statsmodels>=0.14.5",
    "sympy>=1.14.0",
    "xgboost>=3.1.0",
    "yfinance>=0.2.66",
]
